---
language: ruby
before_install:
- openssl version
- if [[ $TRAVIS_OS_NAME == osx ]]; then ./openssl.sh; fi
script: rbx -r openssl -e 'p OpenSSL::OPENSSL_VERSION_NUMBER'
rvm:
- rbx-2.7
os:
- linux
- osx
