---
language: ruby
before_script:
- if [[ $TRAVIS_OS_NAME == osx ]]; then openssl version; fi
- if [[ $TRAVIS_OS_NAME == osx ]]; then "$(brew --prefix openssl)/bin/openssl" version; fi
- if [[ $TRAVIS_OS_NAME == osx ]]; then nm /usr/lib/libssl.dylib | grep SSL_CTX; fi
- if [[ $TRAVIS_OS_NAME == osx ]]; then nm "$(brew --prefix openssl)/lib/libssl.dylib" | grep SSL_CTX fi
script: rbx -r openssl -e 'p OpenSSL::OPENSSL_VERSION_NUMBER'
rvm:
- rbx-2
os:
- linux
- osx
